name: Checks

on:
  - pull_request

env:
  VUE_APP_FATHOM_SITE_ID: xxx
  VUE_APP_GA_ID: xxx

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Install deps
      run: npm install -g npm@7 && npm ci
    - name: Run build
      run: npm run build

  BuildCDK:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Install deps
      run: npm install -g npm@7 && npm ci
    - name: Run build-cdk
      run: npm run build-cdk

  Lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Install deps
      run: npm install -g npm@7 && npm ci
    - name: Run lint
      run: npm run lint