name: Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Install deps
      run: npm install -g npm@7 && npm ci
    - name: Install CDK
      run: npm install -g aws-cdk@2.9.0
    - name: Build Project
      run: npm run build
    - name: Build CDK Templates
      run: npm run build-cdk
    - name: Deploy CDK
      run: |
        cdk deploy --require-approval never
      env:
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
